name = "banasuko"
compatibility_date = "2025-08-26"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

# Environment Variables
[vars]
# Production環境では Cloudflare Pages ダッシュボードで OPENAI_API_KEY を設定