name = "banasuko"
compatibility_date = "2025-08-26"
compatibility_flags = ["nodejs_compat"]

# Pages Functions設定
[build]
command = "npm run build"
cwd = "."

# Environment Variables
[vars]
# Production環境では Cloudflare Pages ダッシュボードで OPENAI_API_KEY を設定